name: surfledger

channels:
  - conda-forge

dependencies:
  - django
  - gunicorn
  - pygrib
  - pip
  - pip:
    - djangorestframework
    - django-webpack-loader 
    - django-widget-tweaks
    - psycopg2
    - first
    - selenium
    - python-dotenv
    - wget
