# Generated by Django 3.0.6 on 2020-05-16 16:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_time', models.DateTimeField(null=True, verbose_name='reference time')),
                ('valid_times', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(verbose_name='valid time'), default=list, size=40)),
                ('sig_ht_comb', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4), default=list, size=40)),
                ('prim_wave_period', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('prim_wave_dir', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('sig_ht_windwaves', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4), default=list, size=40)),
                ('sig_ht_swellwaves1', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4), default=list, size=40)),
                ('sig_ht_swellwaves2', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4), default=list, size=40)),
                ('mean_windwave_period', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('mean_swellwave_period1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('mean_swellwave_period2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('windwave_dir', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('swellwave1_dir', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('swellwave2_dir', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('wind_speed', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=4), default=list, size=40)),
                ('wind_dir', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=40)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapi.Spot')),
            ],
        ),
    ]
