# Generated by Django 3.0.7 on 2020-06-12 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='sig_ht_comb',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=40),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='sig_ht_swellwaves1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=40),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='sig_ht_swellwaves2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=40),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='sig_ht_windwaves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=40),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_speed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=40),
        ),
    ]
